{{- if .Values.web.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vpn-ios-profile.fullname" . }}-web
  labels:
    {{- include "vpn-ios-profile.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "vpn-ios-profile.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "vpn-ios-profile.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
      containers:
        - name: web
          image: nginxinc/nginx-unprivileged
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
          - name: iosprofiles
            mountPath: /usr/share/nginx/html
            readOnly: true
      volumes:
      - name: iosprofiles
        secret:
          secretName: {{ include "vpn-ios-profile.fullname" . }}-ios-profile
          # defaultMode: 0444
{{- end }}
