{{- if and .Values.web.ingressroute.enabled (and .Values.web.ingressroute.username .Values.web.ingressroute.password) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vpn-ios-profile.fullname" . }}-web-basicauth
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.web.ingressroute.username }}
  password: {{ .Values.web.ingressroute.password }}
{{- end }}
