{{- if .Values.web.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vpn-ios-profile.fullname" . }}-web
  labels:
    {{- include "vpn-ios-profile.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "vpn-ios-profile.selectorLabels" . | nindent 4 }}
{{- end }}
