{{- $dns_name := (index $.Values "ipsec-vpn-server" "vpn" "dns_name") -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vpn-ios-profile.fullname" . }}-ios-profile
  namespace: {{ .Values.namespace }}
stringData:
{{- range (index .Values "ipsec-vpn-server" "users") }}
  vpn-{{ .username }}.mobileconfig: |-
    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
    <plist version="1.0">
    <dict>
      <key>ConsentText</key>
      <dict>
        <key>default</key>
        <string>{{ print ($.Values.iosprofile.ConsentText | replace "%username" .username | replace "%dns_name" $dns_name) }}</string>
      </dict>
      <key>HasRemovalPasscode</key>
      <false/>
      <key>PayloadContent</key>
      <array>
        {{- include "vpn.always" (dict "root" $ "user" . ) | nindent 8 }}
      </array>
      <key>PayloadDisplayName</key>
      <string>{{ print ($.Values.iosprofile.PayloadDisplayName | replace "%username" .username | replace "%dns_name" $dns_name) }}</string>
      <key>PayloadDescription</key>
      <string>{{ print ($.Values.iosprofile.PayloadDescription | replace "%username" .username | replace "%dns_name" $dns_name) }}</string>
      <key>PayloadIdentifier</key>
      <string>{{ print ($.Values.iosprofile.PayloadIdentifier | replace "%username" .username | replace "%dns_name" $dns_name) }}</string>
      <key>PayloadOrganization</key>
      <string>{{ print ($.Values.iosprofile.PayloadOrganization | replace "%username" .username | replace "%dns_name" $dns_name) }}</string>
      <key>PayloadRemovalDisallowed</key>
      <false/>
      <key>PayloadType</key>
      <string>Configuration</string>
      <key>PayloadUUID</key>
      <string>{{ sha1sum (printf "%s-%s-%s" $dns_name .username "ios-profile") | upper }}</string>
      <key>PayloadVersion</key>
      <integer>1</integer>
    </dict>
    </plist>
{{- end }}
