name: Release
on:
  release:
    types: [published]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.repository == 'taskmedia/helm_vpn-ios-profile'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Helm
        run: |
          curl -L https://git.io/get_helm.sh | bash -s -- -v v3.7.1

      - name: Create release binary
        run: |
          helm  dependency update

      - name: Create release binary
        run: |
          helm package ./ --destination release/

      - name: Update Index
        env:
          GH_PAGES_URL: github.com/taskmedia/helm
          REPO_NAME: vpn-ios-profile
          HELM_URL: https://helm.task.media/
        run: |
          rm -rf ./gh-pages.zip
          rm -rf ./repo
          curl -sSLO https://${GH_PAGES_URL}/archive/gh-pages.zip
          unzip -o ./gh-pages.zip -d ./repo/
          mv -f ./repo/helm-gh-pages/* ./repo
          rm -rf ./repo/helm-gh-pages/
          cp ./release/*tgz ./repo/${REPO_NAME}/
          cp ./README.md ./repo/${REPO_NAME}/index.md
          helm repo index --merge ./repo/index.yaml --url ${HELM_URL} ./repo

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          repository-name: taskmedia/helm
          branch: gh-pages
          ssh-key: ${{ secrets.DEPLOY_KEY_BLOG }}
          folder: repo
          clean: false
